### PR TITLE
Merge changes back to master

### PR DESCRIPTION
**Pull request by KenaiTheWolf**

### CODE REVIEW

**Comment by Bluebie** [comment]
but.. the readme isn't in markdown? some of the list items are done with ascii heart bullets..

do you actually care about this project? i can just give it to you if you like. I just use steam's ps4 controller support to get this functionality now.

**Comment by The-Wolf312** [comment]
I was just setting up gh-pages. I don't feel like I'm at the skill level at which I could actually take on this project. I think it's neat and I'd like to help but I don't think I can do much more than a little HTML at this point in time.

**Comment by Bluebie** [comment]
ok ¯\\\_(ツ)\_\/¯

**Comment by KenaiTheWolf** [comment]
Could you open a new branch and call it gh-pages? I have another branch I'd like to push.

**Pull request merged**
